# Generated by Django 5.1.6 on 2025-03-04 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_investmentplan_investmentpurchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentplan',
            name='expected_returns',
            field=models.DecimalField(decimal_places=2, default=10, help_text='Expected returns in percentage', max_digits=10),
            preserve_default=False,
        ),
    ]
