# Generated by Django 5.1.6 on 2025-03-04 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_investmentplan_expected_returns'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investmentplan',
            name='expected_returns',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
