# Generated by Django 5.1.6 on 2025-03-06 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_activeinvestment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activeinvestment',
            name='amount',
        ),
    ]
