# Generated by Django 5.1.6 on 2025-03-06 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_activeinvestment_amount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InvestmentPurchase',
        ),
    ]
