# Generated by Django 5.1.7 on 2025-03-07 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_investmentpurchase'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepositWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Bitcoin', 'Bitcoin'), ('Ethereum', 'Ethereum'), ('USDT_BEP20', 'USDT BEP20'), ('USDT_ERC20', 'USDT ERC20'), ('USDT_TRC20', 'USDT TRC20')], max_length=20, unique=True)),
                ('address', models.CharField(max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
