[build]
builder = "NIXPACKS"
buildCommand = "pip install -r requirements.txt && python manage.py migrate && python manage.py collectstatic --noinput "

[start]
cmd = "gunicorn investment_platform.wsgi --bind 0.0.0.0:$PORT"
